name: t_store
description: This is our ecommerce shopping app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'



#--------------- PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http:
  intl:
  logger:
  lottie: ^2.7.0 #the latest version may not be working
  url_launcher:
  flutter_native_splash:
  smooth_page_indicator: ^1.2.0+3
  shimmer:


  # Icons
  iconsax:
  cupertino_icons:

  # State Management
  get:
  get_storage:

  # Product Specific
  readmore:
  carousel_slider:
  flutter_rating_bar:
  capped_progress_indicator:
  connectivity_plus: ^5.0.1 #use 5.0.1 latest version is problematic

  # Firebase
  firebase_storage:
  firebase_core: #^2.23.0
  firebase_auth: #^4.14.0
  cloud_firestore: #^5.5.0




#--------------- ./ PACKAGES END ------------------#
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  flutter_launcher_icons:

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/appIcon.jpg"

  web:
    generate: true
    image_path: "assets/icons/appIcon.jpg"
    background_color: "#00FB9E"
    theme_color: "#00FB9E"
  windows:
    generate: true
    image_path: "assets/icons/appIcon.jpg"
    icon_size: 48 # 
  

flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/products/
    - assets/images/content/
    - assets/images/reviews/
    - assets/icons/categories/
    - assets/icons/payment_methods/


  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800