// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZJWUM_C3Kejp4OtSvJqNznijHvdC4SGM',
    appId: '1:392688599278:web:0d72d1bba3049a260433ff',
    messagingSenderId: '392688599278',
    projectId: 'ecommerceapp-a7606',
    authDomain: 'ecommerceapp-a7606.firebaseapp.com',
    storageBucket: 'ecommerceapp-a7606.firebasestorage.app',
    measurementId: 'G-JTQ7YKFER3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg_vrgkYKrAwlY7hku7usNr52JvbcRd5w',
    appId: '1:392688599278:android:ca93ca117111decb0433ff',
    messagingSenderId: '392688599278',
    projectId: 'ecommerceapp-a7606',
    storageBucket: 'ecommerceapp-a7606.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAztws2XGSTxTzhNbieqGv75qLRBkbZze4',
    appId: '1:392688599278:ios:84ca0145fb22dcb90433ff',
    messagingSenderId: '392688599278',
    projectId: 'ecommerceapp-a7606',
    storageBucket: 'ecommerceapp-a7606.firebasestorage.app',
    androidClientId: '392688599278-sdlfvm5d7ugbbd0do4gbc00ahmr4tm3u.apps.googleusercontent.com',
    iosClientId: '392688599278-a4aotrb00ggrk1jk6ptv3vh51l7p2s6r.apps.googleusercontent.com',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAztws2XGSTxTzhNbieqGv75qLRBkbZze4',
    appId: '1:392688599278:ios:84ca0145fb22dcb90433ff',
    messagingSenderId: '392688599278',
    projectId: 'ecommerceapp-a7606',
    storageBucket: 'ecommerceapp-a7606.firebasestorage.app',
    androidClientId: '392688599278-sdlfvm5d7ugbbd0do4gbc00ahmr4tm3u.apps.googleusercontent.com',
    iosClientId: '392688599278-a4aotrb00ggrk1jk6ptv3vh51l7p2s6r.apps.googleusercontent.com',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZJWUM_C3Kejp4OtSvJqNznijHvdC4SGM',
    appId: '1:392688599278:web:5f85b942a675a7e60433ff',
    messagingSenderId: '392688599278',
    projectId: 'ecommerceapp-a7606',
    authDomain: 'ecommerceapp-a7606.firebaseapp.com',
    storageBucket: 'ecommerceapp-a7606.firebasestorage.app',
    measurementId: 'G-6BLGG8TWQ5',
  );

}